### ISSUE TITLE
Newe Feature: add document preview on consultation request.

### ISSUE THREAD

**Issue by oscar-admin** [oscaremr/oscar#156]

**Comment by oscar-admin** [comment]
zhouzh@ubuntu-annie:~/Downloads$ /usr/lib/jvm/java-6-sun/bin/java -version
java version "1.6.0_26"
Java(TM) SE Runtime Environment (build 1.6.0_26-b03)
Java HotSpot(TM) Server VM (build 20.1-b02, mixed mode)

When I tried to review tiff file, I got the error: 
015-02-11 12:55:37,429 ERROR [ManageDocumentAction:666] Error
java.io.IOException: Bad endianness tag (not 0x4949 or 0x4d4d).
	at com.sun.media.jai.codecimpl.CodecUtils.toIOException(CodecUtils.java:76)
	at com.sun.media.jai.codecimpl.TIFFImageDecoder.getNumPages(TIFFImageDecoder.java:98)
	at org.oscarehr.document.web.ManageDocumentAction.viewDocPage(ManageDocumentAction.java:628)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)

Annie

**Comment by zhoulingmin** [comment]
@annie-zhou 

You need to install JAI library when previewing tiff file:
wget http://download.java.net/media/jai/builds/release/1_1_3/jai-1_1_3-lib-linux-amd64-jdk.bin
% cd $JDK
% chmod u+x $downloaddir/jai-1_1_3-lib-linux-amd64-jdk.bin
% sudo $downloaddir/jai-1_1_3-lib-linux-amd64-jdk.bin

Here's install instruction: 
http://download.java.net/media/jai/builds/release/1_1_3/INSTALL.html

Just a reminder, you need to make sure tomcat server is running with sun-jdk environment.
You can change the default JAVA_HOME environment variable for tomcat server in /etc/default/tomcat6.  Or you can export JAVA_HOME, JRE_HOME and CLASSPATH in ~/.profile.

**Comment by huchengyi** [comment]
it is fixed
